# Generated by Django 4.1.3 on 2022-11-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_ordertype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ordertype',
            name='name',
        ),
    ]
