# Generated by Django 4.1.3 on 2022-11-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_ordertype_code_remove_ordertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
