# Generated by Django 4.1.3 on 2022-11-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_trade_order_type_delete_ordertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
