# Generated by Django 4.1.3 on 2022-11-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_delete_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='total',
        ),
    ]
