# Generated by Django 4.1.3 on 2022-11-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_rename_price_trade_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stocks quantity'),
        ),
    ]
