# Generated by Django 4.1.3 on 2022-11-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_inventory_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
